### PR TITLE
add Contributor Covenant code of conduct

### LINKED ISSUE #3: Clarify code of conduct
@zeke mentioned in another issue:

> The Electron maintainers group has a code of conduct. Please read and agree to it and we'll get you set up.

This was the first I heard about that and am certain that I did not sign that when invited to the `electron-userland` group. If this is a new requirement perhaps it could be added to the description here: https://github.com/electron-userland/about

### PR DESCRIPTION
**Pull request by zeke**
This PR adds a code of conduct to the org. The pledge:

> In the interest of fostering an open and welcoming environment, we as
contributors and maintainers pledge to making participation in our project and
our community a harassment-free experience for everyone, regardless of age, body
size, disability, ethnicity, gender identity and expression, level of experience,
nationality, personal appearance, race, religion, or sexual identity and
orientation.

See http://contributor-covenant.org for more info.

Fixes #3

### CODE REVIEW

**Comment by johnmuhl** [comment]
I feel like there is some latitude in using the Contributor Covenant but from my reading it looks like:

> ...adding an explicit CODE_OF_CONDUCT.md to your project repository.

means we need to add that file to each repo in the org. 

I checked and not every repo in the electron org has the file so perhaps it is enough to only add it in the about repo. Is that just an oversight in a couple of electron repos or a misunderstanding on my part?

If it should be added to every repo I'd prefer to hold off on merging this until we have those COC.md files in place.

**Comment by malept** [comment]
FWIW Electron Packager and Electron Forge (and related) link to Electron's CoC in the contributing docs.

**Comment by zeke** [comment]
I'm personally okay with linking directly to [contributor-covenant.org](http://contributor-covenant.org/), and don't think the ceremony of maintaining all those markdown files is really necessary. Alternatively, each repo's readme (or CONTRIBUTING.MD) could have something like this to make the CoC more discoverable:

```
## Code of Conduct

This project adheres to the Contributor Covenant 
[code of conduct](http://contributor-covenant.org). 
By participating, you are expected to uphold this code.
```

This approach will probably become even more attractive as we continue to [internationalize Electron's docs](https://github.com/electron/electron/pull/9784#issuecomment-309172489).

**Comment by johnmuhl** [comment]
> I'm personally okay with linking directly to contributor-covenant.org, and don't think the ceremony of maintaining all those markdown files is really necessary. Alternatively, each repo's readme (or CONTRIBUTING.MD) could have something ... to make the CoC more discoverable

Adding it to an existing README or CONTRIBUTING doc sounds good (better than a new doc) to me but the same concern stands. I'd rather have each repo/stakeholder be notified and actively opt-in before any org-wide action is taken.

The concern is based on text from the CC:

> Do not simply add the Contributor Covenant to your project and assume that any problems with civility, harassment, or discrimination will be solved. As a project maintainer you must be committed to enforcing the code of conduct. A code of conduct without enforcement sends a false signal that your project is welcoming and inclusive, and can create a dangerous situation for marginalized people who participate. Adding the Contributor Covenant to a project places responsibility on the project team that must not be taken lightly.

I'm trying not to take it lightly and make sure we have team wide buy-in with these responsibilities.

**Comment by zeke** [comment]
> I'm trying not to take it lightly and make sure we have team wide buy-in with these responsibilities.

👍 

I will mention this issue in Electron's Slack to get more eyes on it.

**Comment by paulcbetts** [comment]
+:100:

**Comment by johnmuhl** [comment]
Do we have an `electron-userland` email address to use for reporting? Is there an alternative form of reporting that might work; e.g could we also use electron@github.com?

**Comment by zeke** [comment]
> I'll open some PRs following that example and see how it goes.

Thanks @johnmuhl

**Comment by zeke** [comment]
Thanks for doing the rounds on the repos, @johnmuhl. 🙏

**Comment by johnmuhl** [comment]
Well I only got it added to 1 of the 2 repos I tried but if everyone else is fine with a top down mandate and forcing maintainers into some CoC so be it.

**Pull request merged**
